Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access and HTTP access on the inbound port
      GroupName: AllowAllTraffic1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  UbuntuInstance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      KeyName: "sap-key"
      ImageId: "ami-053b0d53c279acc90"
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: "Ubuntu"
      SecurityGroupIds:
        - !GetAtt "InstanceSecurityGroup.GroupId"
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo apt-get update -y
            sudo apt-get install -y apache2
            sudo ufw allow -y 'Apache'
            sudo systemctl start apache2
            sudo systemctl enable apache2
            echo Hello World from $(hostname -f) > /var/www/html/index.html
Outputs:
  outputInstanceSecurityGroup:
    Description: A reference to the created security group
    Value: !Ref InstanceSecurityGroup
  outputUbuntuInstance:
    Description: A reference to the created EC2 Instance
    Value: !Ref UbuntuInstance
  PublicIpAddress:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt UbuntuInstance.PublicIp