---
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-008b85aa3ff5c1b02
      InstanceType: t2.micro
      KeyName: redhat.linux
      SecurityGroups:
        - !Ref sec20grphttpallow
  sec20grphttpallow:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription : SG to create
      GroupName: mysecgrp
      SecurityGroupIngress : 
       - IpProtocol : tcp
         FromPort : 80
         ToPort : 80
         CidrIp : 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
