---
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-008b85aa3ff5c1b02
      InstanceType: t2.micro
      AvailabilityZone: ap-south-1a
    DeletionPolicy: Retain
  NewVolume:
    Type: AWS::EC2::Volume
    Properties: 
      Size: 100
      Encrypted: true
      AvailabilityZone: ap-south-1a
      Tags:
        - Key: MyTag
          Value: TagValue
    DeletionPolicy: Snapshot
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref MyEC2Instance
      VolumeId: !Ref NewVolume
      Device: /dev/sdh    
  