---
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-008b85aa3ff5c1b02
      InstanceType: t2.micro
      KeyName: redhat.linux
      BlockDeviceMappings:
       - 
         DeviceName: /dev/sdf
         Ebs:
           VolumeType: io1
           Iops: 200
           DeleteOnTermination: true
           VolumeSize: 5
  MyElasticIp:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref MyEC2Instance