AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-new-bucket-s3
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 365
            Transitions:
             - TransitionInDays: 1
               StorageClass: GLACIER
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: 'arn:aws:sns:ap-south-1:730563286606:lkjhgfds-MySNSTopic-DgjK58AhnFHM'
            Event: 's3:ReducedRedundancyLostObject'
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the sample Amazon S3 bucket with a lifecycle configuration

    #this is my s3 bucket logs with inventory