Parameters:
  MyAWSamiID:
    Description: Select the latest Amazon Linux 2 AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64
Resources:
  MyAlcInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref MyAWSamiID
      InstanceType: t2.micro
      SecurityGroups:
        - !ImportValue SSHalcSecGroup

