Parameters: 
  InstanceType:
    Description: parameter to allocate
    Type: String
    Default: "t2.small"
    AllowedValues:
         - "t2.micro"
         - "t2.nano"
         - "t2.small"
    ConstraintDescription: One Must Select the type
  SecurityGroupCIDRIngress:
    Description: Parameters for security group ingress cidr
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: (\d{1,3}).(\d{1,3}).(\d{1,3}).(\d{1,3})/(\d{1,2})
    Default: 0.0.0.0/0
    ConstraintDescription: Must be a valid ip cidr range from 
    x.x.x.x/x
  SecurityGroupsPort:
    Description: Choose the num
    Type: Number
    Default: 22
    AllowedValues:
         - 22
         - 80
    MinValue: 10
    MaxValue: 1500
  AppSubnet:
    Type: List<AWS::EC2::Subnet::Id>
  KeyName: 
    Description: Choose the kay
    Type: AWS::EC2::KeyPair::KeyName
  myVPCID:
    Description: Choose the VPC
    Type: AWS::EC2::VPC::Id
  myPasswd: 
    Description: Choose the password
    Type: String
    NoEcho: true

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-008b85aa3ff5c1b02
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref AppSubnet
  SecGrphttpAllow:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription : SG to create
      GroupName: ProductName
      SecurityGroupIngress : 
       - IpProtocol : tcp
         FromPort : !Ref SecurityGroupsPort
         ToPort : !Ref SecurityGroupsPort
         CidrIp : !Ref SecurityGroupCIDRIngress
      VpcId: !Ref myVPCID